// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Product struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// 定义一个k/v类型，key是string类型，value也是string类型
	Attrs                map[string]*Result `protobuf:"bytes,2,rep,name=attrs,proto3" json:"attrs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetAttrs() map[string]*Result {
	if m != nil {
		return m.Attrs
	}
	return nil
}

type Result struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{1}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Result) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func init() {
	proto.RegisterType((*Product)(nil), "proto.Product")
	proto.RegisterMapType((map[string]*Result)(nil), "proto.Product.AttrsEntry")
	proto.RegisterType((*Result)(nil), "proto.Result")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899) }

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 185 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0x2d, 0x4e, 0xd7,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0xd3, 0x19, 0xb9, 0xd8, 0x03, 0x8a,
	0xf2, 0x53, 0x4a, 0x93, 0x4b, 0x84, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15,
	0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x21, 0x7d, 0x2e, 0xd6, 0xc4, 0x92, 0x92, 0xa2, 0x62, 0x09,
	0x26, 0x05, 0x66, 0x0d, 0x6e, 0x23, 0x49, 0x88, 0x6e, 0x3d, 0xa8, 0x16, 0x3d, 0x47, 0x90, 0x9c,
	0x6b, 0x5e, 0x49, 0x51, 0x65, 0x10, 0x44, 0x9d, 0x94, 0x3b, 0x17, 0x17, 0x42, 0x50, 0x48, 0x80,
	0x8b, 0x39, 0x3b, 0xb5, 0x12, 0x6a, 0x22, 0x88, 0x29, 0xa4, 0xcc, 0xc5, 0x5a, 0x96, 0x98, 0x53,
	0x9a, 0x2a, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x6d, 0xc4, 0x0b, 0x35, 0x30, 0x28, 0xb5, 0xb8, 0x34,
	0xa7, 0x24, 0x08, 0x22, 0x67, 0xc5, 0x64, 0xc1, 0xa8, 0x64, 0xc0, 0xc5, 0x06, 0x11, 0x04, 0x19,
	0x52, 0x5a, 0x94, 0x03, 0x33, 0xa4, 0xb4, 0x28, 0x47, 0x48, 0x84, 0x8b, 0xb5, 0x24, 0xb3, 0x24,
	0x07, 0x62, 0x08, 0x67, 0x10, 0x84, 0x93, 0xc4, 0x06, 0x36, 0xca, 0x18, 0x10, 0x00, 0x00, 0xff,
	0xff, 0x64, 0x5b, 0xd2, 0x3c, 0xe6, 0x00, 0x00, 0x00,
}
